### ISSUE TITLE
implement routing mechanism with react-router-dom

### ISSUE THREAD

**Issue by pratikpakhale** [GDSC-IIIT-Dharwad/bookingcom-frontend#25]
Implement routing with [react-router-dom](https://www.npmjs.com/package/react-router-dom). And render <Home /> component for '/' route

**Comment by NikhilKarthik024** [comment]
i will take it up!

**Comment by pratikpakhale** [comment]
go ahead!

**Comment by C-NikhilKarthik** [comment]
i completed this like 2 weeks ago
https://github.com/GDSC-IIIT-Dharwad/bookingcom-frontend/commit/e1cfe7c2693d23f40745228021a1ed095e4c10c6
pr #28
