### ISSUE TITLE
Add a new page - Hotel List

### ISSUE THREAD

**Issue by pratikpakhale** [GDSC-IIIT-Dharwad/bookingcom-frontend#26]
Refer to this Figma - [Prototype](https://www.figma.com/proto/C8gZzt4G32ApwYhCfiZFo5/GDSC-Booking-Website?node-id=407%3A69&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2)

Initially only build the following search card - 
![image](https://user-images.githubusercontent.com/48487283/215548690-e9954a66-1175-4d8a-9823-0756b98166b0.png)

NOTE - Start working on this issue after #25 is closed successfully.

**Comment by Anish-kumar7641** [comment]
i will work on this

**Comment by pratikpakhale** [comment]
go ahead! but wait until #25 is resolved
