### ISSUE TITLE
Update Hotel Listing Page

### ISSUE THREAD

**Issue by pratikpakhale** [GDSC-IIIT-Dharwad/bookingcom-frontend#27]
Refer to this Figma - [Prototype](https://www.figma.com/proto/C8gZzt4G32ApwYhCfiZFo5/GDSC-Booking-Website?node-id=407%3A69&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2)

Implement the dynamic hotel list - 
![image](https://user-images.githubusercontent.com/48487283/215549405-4d36c933-c432-41c9-9ae0-8fdc4a5a6a80.png)

NOTE - Implement this after #26 is solved

**Comment by NikhilKarthik024** [comment]
I am willing to taking it up!

**Comment by pratikpakhale** [comment]
let others pick a few issues. work on assigned issues first

**Comment by Anand930singh** [comment]
i am willing to take it up

**Comment by pratikpakhale** [comment]
go ahead
