### ISSUE TITLE
Creating a landing/loading page

### ISSUE THREAD

**Issue by C-NikhilKarthik** [GDSC-IIIT-Dharwad/bookingcom-frontend#33]
## Problem
The images load slowly in the home or hotel pages.

## Description
The above stated problem can be easily resolved by adding a landing page / Loader component till the image / page loads. We can also add lazy loading to improve the website.

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by Anand930singh** [comment]
I will take up this issue.

**Comment by pratikpakhale** [comment]
go ahead Anand.
